import { Suspense } from "react";
import Spline from "@splinetool/react-spline";
export default function SplineApp() {
  return (
    <div
      className="h-full w-full bg-gradient-to-b from-[#111111] to-[#000000]"
      style={{
        backgroundImage: "url('2k_stars_milky_way.webp')",
        // backgroundImage: "url('ebf92832fd0e8ef1744ddd9de4afc820.png')",
      }}
    >
      <Suspense
      //   fallback={
      //     <div className="flex h-full w-full justify-center text-center align-middle">
      //       <img src="/public/loading.gif" />
      //     </div>
      //   }
      >
        <Spline scene="https://prod.spline.design/cXHxMnoVz3A6lxlH/scene.splinecode" />
      </Suspense>
    </div>
  );
}

/*
  Auto-generated by Spline
*/

// import useSpline from "@splinetool/r3f-spline";
// import { OrthographicCamera } from "@react-three/drei";

// export default function Scene({ ...props }) {
//   const { nodes, materials } = useSpline(
//     "https://prod.spline.design/cXHxMnoVz3A6lxlH/scene.splinecode"
//   );
//   return (
//     <>
//       <color attach="background" args={["#242424"]} />
//       <group {...props} dispose={null}>
//         <directionalLight
//           name="Sun Light"
//           castShadow
//           intensity={1}
//           shadow-mapSize-width={1024}
//           shadow-mapSize-height={1024}
//           shadow-camera-near={-10000}
//           shadow-camera-far={100000}
//           shadow-camera-left={-1250}
//           shadow-camera-right={1250}
//           shadow-camera-top={1250}
//           shadow-camera-bottom={-1250}
//           color="#fbeeda"
//           position={[0, 16002.91, -27591.33]}
//         />
//         <OrthographicCamera
//           name="Camera"
//           makeDefault={true}
//           zoom={0.32}
//           far={50000}
//           near={-100000}
//           position={[1782.8, -1213.4, 3161.98]}
//           rotation={[-0.58, -0.69, -0.4]}
//           scale={1}
//         />
//         <group name="Group" scale={0.1}>
//           <group name="Orbit Paths" position={[0, 0, -478.54]} scale={0.65}>
//             <mesh
//               name="Orbital Path 8"
//               geometry={nodes["Orbital Path 8"].geometry}
//               material={materials["Orbital Path 8 Material"]}
//               castShadow
//               receiveShadow
//               rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//             />
//             <mesh
//               name="Orbital Path 7"
//               geometry={nodes["Orbital Path 7"].geometry}
//               material={materials["Orbital Path 7 Material"]}
//               castShadow
//               receiveShadow
//               rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//             />
//             <mesh
//               name="Orbital Path 6"
//               geometry={nodes["Orbital Path 6"].geometry}
//               material={materials["Orbital Path 6 Material"]}
//               castShadow
//               receiveShadow
//               rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//             />
//             <mesh
//               name="Orbital Path 5"
//               geometry={nodes["Orbital Path 5"].geometry}
//               material={materials["Orbital Path 5 Material"]}
//               castShadow
//               receiveShadow
//               rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//             />
//             <mesh
//               name="Orbital Path 4"
//               geometry={nodes["Orbital Path 4"].geometry}
//               material={materials["Orbital Path 4 Material"]}
//               castShadow
//               receiveShadow
//               rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//             />
//             <mesh
//               name="Orbital Path 2"
//               geometry={nodes["Orbital Path 2"].geometry}
//               material={materials["Orbital Path 2 Material"]}
//               castShadow
//               receiveShadow
//               rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//             />
//             <mesh
//               name="Orbital Path 21"
//               geometry={nodes["Orbital Path 21"].geometry}
//               material={materials["Orbital Path 21 Material"]}
//               castShadow
//               receiveShadow
//               rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//             />
//             <mesh
//               name="Orbital Path"
//               geometry={nodes["Orbital Path"].geometry}
//               material={materials["Orbital Path Material"]}
//               castShadow
//               receiveShadow
//               rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//             />
//           </group>
//           <group name="Sun" position={[0, 0, -478.54]}>
//             <mesh
//               name="Sun1"
//               geometry={nodes.Sun1.geometry}
//               material={materials["Sun1 Material"]}
//               castShadow
//               receiveShadow
//               scale={109}
//             />
//           </group>
//           <group name="Planets" position={[0, 0, -478.54]}>
//             <group name="Mercury">
//               <mesh
//                 name="Mercury1"
//                 geometry={nodes.Mercury1.geometry}
//                 material={materials["Mercury1 Material"]}
//                 receiveShadow
//                 position={[0, 0, 32485.17]}
//                 rotation={[0, 0, 0]}
//                 scale={0.42}
//               />
//             </group>
//             <group name="Venus">
//               <mesh
//                 name="Venus1"
//                 geometry={nodes.Venus1.geometry}
//                 material={materials["Venus1 Material"]}
//                 receiveShadow
//                 position={[0, 0, 35566.53]}
//                 scale={0.85}
//               />
//             </group>
//             <group name="Earth">
//               <mesh
//                 name="Earth1"
//                 geometry={nodes.Earth1.geometry}
//                 material={materials["Earth1 Material"]}
//                 receiveShadow
//                 position={[0, 0, 41944.06]}
//                 scale={1}
//               >
//                 <group name="Moon">
//                   <mesh
//                     name="Moon1"
//                     geometry={nodes.Moon1.geometry}
//                     material={materials["Moon1 Material"]}
//                     castShadow
//                     receiveShadow
//                     position={[0, 0, 580]}
//                     scale={0.25}
//                   />
//                 </group>
//               </mesh>
//             </group>
//             <group name="Mars" position={[0, 0, 52362.11]}>
//               <mesh
//                 name="Mars1"
//                 geometry={nodes.Mars1.geometry}
//                 material={materials["Mars1 Material"]}
//                 receiveShadow
//                 position={[0, 0, -8180.07]}
//                 scale={0.52}
//               />
//             </group>
//             <group name="Jupiter" position={[0, 0, 49836.81]}>
//               <mesh
//                 name="Jupiter1"
//                 geometry={nodes.Jupiter1.geometry}
//                 material={materials["Jupiter1 Material"]}
//                 castShadow
//                 receiveShadow
//                 scale={11}
//               />
//             </group>
//             <group name="Saturn" position={[0, 0, 59998.46]}>
//               <group name="Saturn1" rotation={[0, -Math.PI / 2, 0]}>
//                 <mesh
//                   name="Ring"
//                   geometry={nodes.Ring.geometry}
//                   material={materials[""]}
//                   rotation={[-1.75, 0, Math.PI / 2]}
//                   scale={[90, 90, 1]}
//                 />
//                 <mesh
//                   name="Saturn2"
//                   geometry={nodes.Saturn2.geometry}
//                   material={materials["Saturn2 Material"]}
//                   receiveShadow
//                   rotation={[0, 0, 0]}
//                   scale={9}
//                 />
//               </group>
//             </group>
//             <group name="Uranus">
//               <mesh
//                 name="Uranus1"
//                 geometry={nodes.Uranus1.geometry}
//                 material={materials["Uranus1 Material"]}
//                 castShadow
//                 receiveShadow
//                 position={[0, 0, 66709.79]}
//                 scale={4}
//               />
//             </group>
//             <group name="Neptune">
//               <mesh
//                 name="Neptune1"
//                 geometry={nodes.Neptune1.geometry}
//                 material={materials["Neptune1 Material"]}
//                 castShadow
//                 receiveShadow
//                 position={[0, 0, 70439.45]}
//                 scale={4}
//               />
//             </group>
//           </group>
//         </group>
//         <hemisphereLight
//           name="Default Ambient Light"
//           intensity={0.45}
//           color="#f7f5f1"
//         />
//       </group>
//     </>
//   );
// }
